<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\ </SolutionDir>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Version>3.0.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>Carnac.App</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup>
    <NoWin32Manifest>true</NoWin32Manifest>
  </PropertyGroup>
  <ItemGroup>
    <Page Update="UI\PositionOnMonitorSelector.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Themes\Generic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\PreferencesView.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>
      </SubType>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
    <Resource Include="Resources\Entypo.ttf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="carnac_2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="icon.embedded.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\WindowsIcons-license.txt" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Entypo-license.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="MahApps.Metro.Resources" Version="0.6.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Reactive" Version="6.0.0" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\w4b.carnac.logic\w4b.carnac.logic.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>